# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

development:
  enabled: true
  storage_path: /data/openstack-helm/postgresql

replicas: 1 #only 1 replica currently supported

service_name: postgresql

# using dockerhub postgresql: https://hub.docker.com/r/library/postgres/tags/
images:
  postgresql: "docker.io/postgres:9.5"
  pull_policy: IfNotPresent

volume:
  class_path: volume.beta.kubernetes.io/storage-class
  class_name: general
  size: 20Gi

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port:
    postgresql: 5432
