apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-etc
data:
  named.conf.options: |+
{{ tuple "etc/_region-dns-config.tpl" . | include "template" | indent 4 }}
  secret: |
{{ tuple "etc/_secret.tpl" . | include "template" | indent 4 }}
