apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maas-rack
spec:
  template:
    metadata:
      labels:
        app: maas-rack-controller
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      hostNetwork: true
      dnsPolicy: ClusterFirst
      containers:
      - name: maas-rack
        image: {{ .Values.images.maas_rack }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        {{- if .Values.resources.enabled }}
        resources:
          limits:
            cpu: {{ .Values.resources.maas_rack_controller.limits.cpu | quote }}
            memory: {{ .Values.resources.maas_rack_controller.limits.memory | quote }}
          requests:
            cpu: {{ .Values.resources.maas_rack_controller.requests.cpu | quote }}
            memory: {{ .Values.resources.maas_rack_controller.requests.memory | quote }}
        {{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: registerrackcontrollersh
          mountPath: "/usr/local/bin/register-rack-controller.sh"
          subPath: "register-rack-controller.sh"
      volumes:
        - name: registerrackcontrollersh
          configMap:
            name: maas-bin
            defaultMode: 0511
