apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
spec:
  ports:
    - name: db
      port: {{ .Values.network.port.postgresql }}
  selector:
    app: {{ .Values.service_name }}
