# Default values for maas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  maas_region: quay.io/attcomdev/maas-region:2.1.2-1
  maas_rack: quay.io/attcomdev/maas-rack:2.1.2-1
  pull_policy: Always

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port:
    region_container: 80
    service_gui: 80
    service_gui_target: 80
    service_proxy: 8000
    service_proxy_target: 8000

secret: 3858f62230ac3c915f300c664312c63f

service_name: maas-region-ui 

resources:
  enabled: false
  maas_rack_controller:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"
  maas_region:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"
